apiVersion: v1
kind: Service
metadata:
  name: springbootk8s
  labels:
    name: springbootk8s
  spec:
    ports:
      - nodePort: 30163
        port: 8080
       - targetPort: 8080
       - protocol: TCP
      selector:
        app: springbootk8s
      type: NodePort
